"""Generate club badge SVGs and the generic player placeholder.

**These are not the clubs' real crests.** Premier League crests are trademarked and
copyrighted; Wikimedia Commons excludes them by policy, and a survey of all 20 clubs
found exactly one crest SVG under a free licence - a 1930 Arsenal crest. So rather than
mislabel trademarked artwork as open, the project draws its own: a monogram in each
club's real colours, authored here and therefore genuinely ours to license.

Output is deterministic - the same slug always produces a byte-identical file - so
regenerating never shows up as a diff.
"""

from __future__ import annotations

import json
import logging
import re
from datetime import UTC, datetime
from pathlib import Path

from src.data_collection.config import PROJECT_ROOT

logger = logging.getLogger(__name__)

LOGO_DIR = PROJECT_ROOT / "assets" / "logos"
PLAYER_DIR = PROJECT_ROOT / "assets" / "players"
LOGO_MAPPING = LOGO_DIR / "mapping.json"
PLACEHOLDER_NAME = "_placeholder.svg"

#: Primary and secondary colours per club, as the clubs actually play in. These are
#: facts about the clubs rather than design choices, which is why they sit in one table
#: instead of being picked per badge.
CLUB_COLOURS: dict[str, tuple[str, str]] = {
    "arsenal": ("#EF0107", "#FFFFFF"),
    "aston-villa": ("#670E36", "#95BFE5"),
    "bournemouth": ("#DA291C", "#000000"),
    "brentford": ("#E30613", "#FFFFFF"),
    "brighton": ("#0057B8", "#FFCD00"),
    "burnley": ("#6C1D45", "#99D6EA"),
    "chelsea": ("#034694", "#FFFFFF"),
    "coventry": ("#78D0F3", "#FFFFFF"),
    "crystal-palace": ("#1B458F", "#C4122E"),
    "everton": ("#003399", "#FFFFFF"),
    "fulham": ("#000000", "#FFFFFF"),
    "hull": ("#F5A12D", "#000000"),
    "ipswich": ("#3A64A3", "#FFFFFF"),
    "leeds": ("#FFCD00", "#1D428A"),
    "leicester": ("#003090", "#FDBE11"),
    "liverpool": ("#C8102E", "#00B2A9"),
    "luton": ("#F78F1E", "#FFFFFF"),
    "manchester-city": ("#6CABDD", "#1C2C5B"),
    "manchester-united": ("#DA291C", "#FBE122"),
    "newcastle-united": ("#241F20", "#FFFFFF"),
    "norwich": ("#FFF200", "#00A650"),
    "nottingham-forest": ("#DD0000", "#FFFFFF"),
    "sheffield-united": ("#EE2737", "#FFFFFF"),
    "southampton": ("#D71920", "#130C0E"),
    "sunderland": ("#EB172B", "#FFFFFF"),
    "tottenham": ("#132257", "#FFFFFF"),
    "watford": ("#FBEE23", "#ED2127"),
    "west-brom": ("#122F67", "#FFFFFF"),
    "west-ham": ("#7A263A", "#1BB1E7"),
    "wolves": ("#FDB913", "#231F20"),
}

#: Used when a club has no entry above - visible enough that it gets noticed and added.
FALLBACK_COLOURS = ("#52514E", "#FFFFFF")


def club_initials(name: str) -> str:
    """Derive a short code for a club's monogram.

    Multi-word clubs take the initials of the first two words, so "Manchester United"
    reads MU and "Manchester City" reads MC. Single-word clubs take three letters, which
    both matches football's usual three-letter codes and keeps Brentford (BRE) apart
    from Brighton (BRI) - two letters would collide.

    Args:
        name: Club display name, e.g. ``"Manchester United"``.

    Returns:
        A two or three letter uppercase code.
    """
    words = [word for word in re.split(r"[\s\-']+", name) if word]
    if not words:
        return "?"
    if len(words) == 1:
        return words[0][:3].upper()
    return (words[0][0] + words[1][0]).upper()


def badge_svg(slug: str, name: str) -> str:
    """Render one club badge.

    Args:
        slug: Club slug, used to look up colours.
        name: Club display name, used for the monogram and the accessible title.

    Returns:
        A complete SVG document.
    """
    primary, secondary = CLUB_COLOURS.get(slug, FALLBACK_COLOURS)
    letters = club_initials(name)
    # More letters must sit smaller to occupy the same optical width inside the circle.
    font_size = {1: 56, 2: 42}.get(len(letters), 31)

    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" '
        'width="100" height="100" role="img" '
        f'aria-label="{name}">\n'
        "  <!-- Generated by premier-league-predictor. This is a monogram badge drawn by\n"
        "       the project, NOT the club's official crest. Club crests are trademarked\n"
        "       and are not available under an open licence. -->\n"
        f"  <title>{name}</title>\n"
        f'  <circle cx="50" cy="50" r="48" fill="{primary}"/>\n'
        f'  <circle cx="50" cy="50" r="48" fill="none" stroke="{secondary}" stroke-width="4"/>\n'
        f'  <text x="50" y="50" fill="{secondary}" font-size="{font_size}" '
        'font-family="system-ui, -apple-system, Segoe UI, sans-serif" font-weight="700" '
        'text-anchor="middle" dominant-baseline="central">'
        f"{letters}</text>\n"
        "</svg>\n"
    )


def placeholder_svg() -> str:
    """Render the generic player avatar.

    Used for any candidate with no photo under a verified free licence. Drawn here so it
    carries no licence question of its own.

    Returns:
        A complete SVG document.
    """
    return (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" '
        'width="100" height="100" role="img" aria-label="No free-licensed photo available">\n'
        "  <!-- Generated by premier-league-predictor. Shown when no photo of a player\n"
        "       could be confirmed under a free licence. See assets/players/mapping.json\n"
        '       ("placeholders") for who this applies to and why. -->\n'
        "  <title>No free-licensed photo available</title>\n"
        '  <rect width="100" height="100" fill="#E1E0D9"/>\n'
        '  <circle cx="50" cy="38" r="17" fill="#898781"/>\n'
        '  <path d="M50 60c-17 0-30 11-32 27h64c-2-16-15-27-32-27z" fill="#898781"/>\n'
        "</svg>\n"
    )


def generate_badges(clubs: list[tuple[str, str]]) -> dict[str, dict[str, object]]:
    """Write a badge SVG per club and return the mapping entries.

    Args:
        clubs: ``(slug, display name)`` pairs.

    Returns:
        Slug -> mapping entry.
    """
    LOGO_DIR.mkdir(parents=True, exist_ok=True)
    entries: dict[str, dict[str, object]] = {}

    for slug, name in clubs:
        path = LOGO_DIR / f"{slug}.svg"
        path.write_text(badge_svg(slug, name), encoding="utf-8")
        primary, secondary = CLUB_COLOURS.get(slug, FALLBACK_COLOURS)
        if slug not in CLUB_COLOURS:
            logger.warning("No colours defined for %r - using the fallback grey", slug)
        entries[slug] = {
            "team": name,
            "path": f"assets/logos/{slug}.svg",
            "initials": club_initials(name),
            "colours": [primary, secondary],
        }

    logger.info("Generated %d club badges in %s", len(entries), LOGO_DIR)
    return entries


def write_placeholder() -> Path:
    """Write the generic player avatar.

    Returns:
        The path written.
    """
    PLAYER_DIR.mkdir(parents=True, exist_ok=True)
    path = PLAYER_DIR / PLACEHOLDER_NAME
    path.write_text(placeholder_svg(), encoding="utf-8")
    logger.info("Wrote %s", path)
    return path


def write_logo_mapping(entries: dict[str, dict[str, object]]) -> Path:
    """Write ``assets/logos/mapping.json``.

    Args:
        entries: Output of :func:`generate_badges`.

    Returns:
        The path written.
    """
    payload = {
        "generated_at": datetime.now(UTC).isoformat(),
        "note": (
            "Monogram badges generated by this project in each club's colours. These are "
            "NOT official club crests - Premier League crests are trademarked and are not "
            "available under an open licence."
        ),
        "licence": "Generated by this project; reuse freely.",
        "logos": entries,
    }
    LOGO_MAPPING.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
    logger.info("Wrote %s", LOGO_MAPPING)
    return LOGO_MAPPING


def build_all(clubs: list[tuple[str, str]]) -> dict[str, dict[str, object]]:
    """Generate every badge, the placeholder, and the logo mapping.

    Args:
        clubs: ``(slug, display name)`` pairs.

    Returns:
        The mapping entries.
    """
    entries = generate_badges(clubs)
    write_placeholder()
    write_logo_mapping(entries)
    return entries
